# Generated by Django 5.2.12 on 2026-04-07 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingIntentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_type', models.CharField(choices=[('payment', 'Payment')], max_length=50)),
                ('status', models.CharField(choices=[('collecting', 'Collecting'), ('ready_for_confirmation', 'Ready for confirmation'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='collecting', max_length=40)),
                ('collected_data_json', models.JSONField(default=dict)),
                ('missing_fields_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_prompt_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_sessions', to='ai_agent.promptrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_intent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'collecting')), fields=('user', 'intent_type'), name='unique_collecting_pending_intent_per_user')],
            },
        ),
    ]
