# Generated by Django 5.2.12 on 2026-04-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_pendingintentsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingintentsession',
            name='intent_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('product_search', 'Product search')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingintentsession',
            name='status',
            field=models.CharField(choices=[('collecting', 'Collecting'), ('ready_for_confirmation', 'Ready for confirmation'), ('results_ready', 'Results ready'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='collecting', max_length=40),
        ),
    ]
