# Generated by Django 5.2.12 on 2026-04-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0003_alter_pendingintentsession_intent_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingintentsession',
            name='intent_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('product_search', 'Product search'), ('swap', 'Swap')], max_length=50),
        ),
    ]
