# Generated by Django 5.2.12 on 2026-04-06 21:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_agent', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_address', models.CharField(blank=True, max_length=255, null=True)),
                ('token_symbol', models.CharField(max_length=30)),
                ('token_address', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=24, null=True)),
                ('currency', models.CharField(max_length=20)),
                ('network', models.CharField(default='Etherlink', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('schedule_in_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_confirmation', 'Awaiting confirmation'), ('confirmed', 'Confirmed'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='awaiting_confirmation', max_length=30)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parsed_intent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intent', to='ai_agent.parsedintent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='wallets.walletprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
