# Generated by Django 5.2.12 on 2026-04-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='explorer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
