# Generated by Django 5.2.12 on 2026-04-09 13:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentintent_confirmed_at_and_more'),
        ('wallets', '0002_walletprofile_encrypted_private_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='execution_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_confirmation', 'Awaiting confirmation'), ('confirmed', 'Confirmed'), ('submitted', 'Submitted'), ('scheduled', 'Scheduled'), ('failed', 'Failed')], default='awaiting_confirmation', max_length=30),
        ),
        migrations.CreateModel(
            name='GiftCardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120)),
                ('query', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('demo', 'Demo'), ('api', 'API')], default='demo', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready')], default='ready', max_length=20)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_requests', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_requests', to='wallets.walletprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('strategy_name', models.CharField(max_length=255)),
                ('strategy_type', models.CharField(max_length=100)),
                ('apy_estimate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('mode', models.CharField(choices=[('demo', 'Demo'), ('real', 'Real')], default='demo', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_positions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_positions', to='wallets.walletprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('send', 'Send'), ('receive', 'Receive'), ('swap', 'Swap'), ('giftcard', 'Gift card'), ('save', 'Save')], max_length=20)),
                ('asset_symbol', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('network', models.CharField(max_length=80)),
                ('recipient_address', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_address', models.CharField(blank=True, max_length=255, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('explorer_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('scheduled', 'Scheduled')], default='pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='payments.paymentintent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='wallets.walletprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
