# Generated by Django 5.2.12 on 2026-04-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentintent_execution_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='registry_contract_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='registry_payment_intent_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='registry_tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
