# Generated by Django 5.2.12 on 2026-04-30 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfidentialAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("confidential_payment", "Confidential payment"),
                            ("confidential_savings", "Confidential savings"),
                            ("confidential_agreement", "Confidential agreement"),
                            ("proof_submission", "Proof submission"),
                            ("general_help", "General help"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("awaiting_wallet", "Awaiting wallet"),
                            ("submitted", "Submitted"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("public_summary", models.TextField()),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("tx_hash", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contract_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("network", models.CharField(default="Sepolia", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confidential_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfidentialAgreementRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("metadata_hash", models.CharField(max_length=66)),
                ("condition_summary", models.TextField()),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("released", "Released"),
                            ("refunded", "Refunded"),
                            ("dispute", "Dispute"),
                            ("proof_submitted", "Proof submitted"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("tx_hash", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contract_agreement_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("ai_verdict", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "ai_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_record",
                        to="confidential.confidentialaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confidential_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavingsPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=30)),
                ("amount_display", models.CharField(max_length=64)),
                ("lock_rule", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("tx_hash", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_position",
                        to="confidential.confidentialaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confidential_savings_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
