# Generated by Django 5.2.12 on 2026-05-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confidential", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingsposition",
            name="unlock_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savingsposition",
            name="withdraw_tx_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="savingsposition",
            name="withdrawn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="confidentialaction",
            name="intent",
            field=models.CharField(
                choices=[
                    ("confidential_payment", "Confidential payment"),
                    ("public_payment", "Public payment"),
                    ("confidential_savings", "Confidential savings"),
                    ("confidential_agreement", "Confidential agreement"),
                    ("proof_submission", "Proof submission"),
                    ("general_help", "General help"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="savingsposition",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("withdrawable", "Withdrawable"),
                    ("withdrawn", "Withdrawn"),
                    ("failed", "Failed"),
                ],
                default="active",
                max_length=30,
            ),
        ),
    ]
