# Generated by Django 5.2.12 on 2026-04-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletprofile',
            name='encrypted_private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
