# Generated by Django 5.2.12 on 2026-04-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_walletprofile_encrypted_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletprofile',
            name='last_balance_refresh_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
